scaleset:
  name: "test"
  runner_group: "default"

auth:
  url: "https://github.com/org/repo"
  app:
    id: "your_app_id"
    installation_id: "your_installation_id"
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      YOUR_PRIVATE_KEY_HERE
      -----END RSA PRIVATE KEY-----

settings:
  min_runners: 1
  max_runners: 10

